### ISSUE TITLE
AsyncAPI duplications finder aka document optimizer

### ISSUE THREAD

**Issue by derberg** [asyncapi/optimizer#1]
Build a library that code-first users would benefit from the most but not only. A library that as the input gets AsyncAPI document and as output provides optimized AsyncAPI document. For example:

- Reuse of components
- Duplicated schemas moved to components and ref-ed from a message
- Remove not used components

The goal is to shrink the document to a minimum.

More requirements:
- There should be flags to disable specific parts of optimization, like removal of not used components for example. 
- The structure of the library should make it easy to add more optimizations that are not listed above.
- I should be able to just get an optimization report, without actually changes, something like `npm publish --dry-run` that just indicates how the package will look like after publishing, without actually publishing it.

Non-functional requirements:
- can be JS or TS, whatever feels better for you
- must be a library that later I can integrate in the UI or CLI. No file system operations. 
- As input, you get an AsyncAPI document parsed with https://github.com/asyncapi/parser-js/. As output, you either get a modified AsyncAPI document or/and just a report of possible optimizations and where they can be done inside the document

Use case:
AsyncAPI offers many different ways to reuse certain parts of the document like messages or schemas definitions or references to external files, not to even mention the traits. There is a need for a tool that can be plugged into any workflows and optimize automatically documents that are generated from code.

**Comment by derberg** [comment]
Welcome to the new repo 🕺🏼

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Hi! Could you check if currently optimizer meets the given requirements described in the issue's description? If not, please create relevant issues, and close the issue. I think the "main" issue is no longer needed :)
