### ISSUE TITLE
Add support for traits optimization.

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/optimizer#13]
The library should be able to support messageTraits optimization. currently, it only supports messages, parameters and schema optimization.

**Comment by magicmatatjahu** [comment]
@KhudaDad414 Is it still valid? I remember you were doing something with messageTraits, but currently we don't support everything yet, am I right?

**Comment by KhudaDad414** [comment]
> @KhudaDad414 Is it still valid? I remember you were doing something with messageTraits, but currently we don't support everything yet, am I right?

Yes it is. We don't support traits optimization yet.
