### ISSUE TITLE
Add JSON and JSON string support for input and output.

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/optimizer#15]
The library currently only supports YAML string files for input and output. It should be able to support JSON and JSON strings as well.

**Comment by KhudaDad414** [comment]
@derberg @jazzyarchitects @jonaslagoni 
First of all, Sorry for pinging you frequently.
Secondly, I have a few questions about implementing this.
For input, I don't think there should be any issues to implement.
About the output, I think we need to give users a way to select the output they want from the `getOptimizedDocument()` method.
I am thinking about an option in Options of `getOptimizedDocument(options)`.
like:
````
{
   "rules":{
      "reuseComponents":true,
      "removeComponents":true,
      "moveToComponents":true
   },
```
   "output": 'JSON' | 'YAML' | 'JSON_STRING'
```
}
````
What do you think?

**Comment by derberg** [comment]
I think it would be cool if someone can choose between JSON or YAML but what do you mean by `JSON_STRING`?

shouldn't it always be a string? no matter if stringified JSON or YAML? I can always parse it, right?
