### ISSUE TITLE
AsyncAPI spec v3 support in Optimizer

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/optimizer#168]
## Problem

Our library is not yet compatible with AsyncAPI v3. This means that users of our library who want to use AsyncAPI v3 will be unable to do so.

## Solution

We will make the necessary updates to our parser and implementation to support AsyncAPI v3. This involves three main tasks:

- [ ] #173
- [x] #172
- [ ] #192

Once https://github.com/asyncapi/parser-js/issues/780 is solved, update parser dependency (might be automated)

## Rabbit Holes

Potential challenges could include unforeseen issues with the parser update.

## Out of bounds

We will not be adding any new features or making any other major changes to the library as part of this bet.

**Comment by jonaslagoni** [comment]
cc codeowners @KhudaDad414 @magicmatatjahu @derberg

Would be really cool to have this library work out the gate when we release v3, are any of you interested in scheduling a public call specifically to discuss how to enable this?

If you have any questions about how it can be achieved or v3-specific stuff I can help answer those in the meeting to enable you to progress with this 🙂 

Let me know if it has any interest.

**Comment by KhudaDad414** [comment]
Thanks @jonaslagoni . I have actually started working on the issue. I will join the next spec 3.0 meeting to discuss the challenges here and have your input on it. 🙏

**Comment by jonaslagoni** [comment]
Awesome 💪
