### ISSUE TITLE
[BUG] File Reading Method in the Example script is not appropriate

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/optimizer#251]
### Describe the bug.

The [example script](https://github.com/asyncapi/optimizer/blob/master/examples/index.js) uses relative paths (./examples/input.yaml and ./examples/output.yaml) to handle file reading and writing operations, it will fail if executed from different directories.

### Expected behavior

The script should manage file paths using the __dirname variable to ensure consistent behaviour irrespective of the current execution directory. This will ensure correct file referencing at all times.

### Screenshots

-

### How to Reproduce

1. clone the project.
2. compile it with `npm run dev`
3. run `cd examples` then `node index.js` 

### 🥦 Browser

Other

### 👀 Have you checked for similar open issues?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md)

### Are you willing to work on this issue ?

No, someone else can work on it

**Comment by omidNM24** [comment]
Hi @KhudaDad414, can I work on this issue?
