### ISSUE TITLE
add bindings optimization support

### ISSUE THREAD

**Issue by KhudaDad414** [asyncapi/optimizer#44]
#### Reason/Context
Since we have a place for different `bindings` in the `components` section like `serverBindings`, `channelBindings`,`operationBindings` and `messageBindings`, we can use those spaces to optimize different bindings.

**Comment by magicmatatjahu** [comment]
I wonder if we should try to make some generic algorithm to process all optimizations. We can make everything manually and write a lot of  code, but it's not a good idea at all. Maybe we should try to use [JSONPath](https://www.npmjs.com/package/jsonpath-plus) to retrieve all needed objects and process given optimization? Then when we will release `3.0.0` release we only add new paths to process and rest won't change. I haven't tested it but you could try it. it's just a loose idea.

What do you think @KhudaDad414 ?

**Comment by KhudaDad414** [comment]
Thanks, @magicmatatjahu 🙇 . Looks promising. I will do some tests and share how it goes.
